AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  InputValidatorAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://cc-chatbot-niknar/swagger.yaml
  LF0:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://cc-chatbot-niknar/547a5fc4276ed5422773e2d9e81ec6bc
      Handler: lex_input_validator.handler
      Events:
        ValidateInputAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: InputValidatorAPI
            Path: /chatbot
            Method: post
      Policies:
      - AmazonLexRunBotsOnly
      - CloudWatchLogsFullAccess
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: s3://cc-chatbot-niknar/547a5fc4276ed5422773e2d9e81ec6bc
      Handler: lex_response_handler.lambda_handler
      Policies:
      - AmazonSQSFullAccess
  LF2:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://cc-chatbot-niknar/547a5fc4276ed5422773e2d9e81ec6bc
      Handler: send_notifications.handler
      Events:
        CloudwatchCronEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSNSFullAccess
      - AmazonDynamoDBReadOnlyAccess
      - AmazonSQSFullAccess
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSQueue
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
